# Usage: ansible-playbook --ask-become-pass local.yml
---
- hosts: fedora
  gather_facts: false
  remote_user: curtis
  become: true
  become_user: root

  tasks:
    - include: roles/common/tasks/etckeeper.yml
