---
- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux_disabled_output
- name: Reboot machine (SELinux policy update)
  reboot:
  when:
    - selinux_disabled_output.reboot_required
